/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlogBlog: typeof import('./src/components/content/main/BlogBlog.vue')['default']
    BlogContent: typeof import('./src/components/BlogContent.vue')['default']
    BlogFooter: typeof import('./src/components/BlogFooter.vue')['default']
    BlogHeader: typeof import('./src/components/BlogHeader.vue')['default']
    BlogIndex: typeof import('./src/components/content/main/BlogIndex.vue')['default']
    BlogResume: typeof import('./src/components/content/main/BlogResume.vue')['default']
    CompanyDetail: typeof import('./src/components/content/main/resumeComp/CompanyDetail.vue')['default']
    EducationInfo: typeof import('./src/components/content/main/resumeComp/EducationInfo.vue')['default']
    MaskArea: typeof import('./src/components/pubComp/MaskArea.vue')['default']
    NavList: typeof import('./src/components/content/NavList.vue')['default']
    PersonalInfo: typeof import('./src/components/content/main/resumeComp/PersonalInfo.vue')['default']
    ProjectDetail: typeof import('./src/components/content/main/resumeComp/ProjectDetail.vue')['default']
    ProjectExp: typeof import('./src/components/content/main/resumeComp/ProjectExp.vue')['default']
    ResumeTitle: typeof import('./src/components/content/main/resumeComp/ResumeTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
